[tox]
env_list = py311, linters
no_package = false

[testenv]
commands =
    pytest --junitxml=unit-tests.xml --cov=wazo_calld_queue --cov=wazo_call_logd_queue --cov-report term --cov-report xml:coverage.xml tests
deps =
    -rrequirements-test.txt
    pytest-cov

[testenv:linters]
skip_install = true
deps = pre-commit
commands = pre-commit run --all-files
