name: wazo-calld-queue
namespace: wazo
version: 2.3.1
author: Sylvain Boily & Mathias WOLFF
display_name: Queue API and events
min_wazo_version: 26.06
tags:
  - queue
homepage: https://github.com/wazo-communication/wazo-calld-queue
